---
- name: Start NTP Server
  service: name=ntpd state=started enabled=yes
  register: command_result
  tags: ntp

- name: Update system date
  command: ntpq -p
  when: command_result.changed
  tags: ntp

- name: NTP Server configuration cleanup
  lineinfile: dest=/etc/ntp.conf regexp="server {{ item }}" state=absent
  with_items:
   - 1
   - 2
   - 3
  when: ntp_server is defined
  tags: ntp

- name: NTP Server configuration update
  lineinfile: dest=/etc/ntp.conf regexp="server 0" line="server {{ ntp_server }} iburst"
  register: command_result
  when: ntp_server is defined
  tags: ntp

- name: Restart NTP service
  service: name=ntpd state=restarted
  when: command_result.changed
  tags: ntp

- name: Update system date
  command: ntpq -p
  when: command_result.changed
  tags: ntp
