---
- hosts: databaseservers
  vars_files:
    - config.yml
  vars:
    db_type: "{{ obm_db_type | default('PGSQL') }}"
  roles:
      - { role: obm-db-pg, when: "db_type == 'PGSQL'" }
      #- { role: obm-db-my, when: "db_type == 'MYSQL'" }
