---
- hosts: databaseservers
  vars_files:
    - config.yml
  vars:
    db_type: "{{ obm_db_type | default('PGSQL') }}"
  roles:
      - { role: postgres, when: "db_type == 'PGSQL'" }
      #- { role: mysql, when: "db_type == 'MYSQL'" }
