---
- name: Deploy saslauthd configuration
  template: src=saslauthd dest=/etc/sysconfig/saslauthd
  notify: 
   - Restart saslauthd
  tags: sasl

- name: Deploy SASL configuration
  template: src={{ item }} dest=/etc
  with_items:
   - pam_ldap_obm.conf
   - saslauthd.conf
  notify: 
   - Restart saslauthd
  tags: sasl
