---
- name: Merge PostgreSQL configuration files
  assemble: src={{ datadir }}/pg_hba.d dest={{ datadir }}/pg_hba.conf backup=yes
  delegate_to: "{{ db_master_host }}"
  notify: 
    - Reload Postgres
  tags: postgres-common

- name: Reload Postgres
  service: name=postgresql state=reloaded
  delegate_to: "{{ db_master_host }}"
  tags: postgres-common
