---
- name: Add OBM APT GPG key [without proxy]
  apt_key: >
    url=http://deb.obm.org/obmgpg.pub
    state=present
  when: mode == "internet" and proxy_host is not defined
  tags: obm-conf

- name: Add OBM APT GPG key [with proxy]
  apt_key: >
    url=http://deb.obm.org/obmgpg.pub
    state=present
  environment: proxy_env
  when: mode == "internet" and proxy_host is defined
  tags: obm-conf

- name: Add OBM APT repositories
  template: >
    src=obm.list
    dest=/etc/apt/sources.list.d/obm.list
    mode=0644
  notify: Update DEB cache
  tags: obm-conf

- name: Add Opush APT repository
  copy: >
    src=opush.list
    dest=/etc/apt/sources.list.d/opush.list
    mode=0644
  notify: Update DEB cache
  tags: obm-conf
