---
- name: Create OBM configuration directory
  file: path=/etc/obm/conf state=directory
  tags: obm-conf

- name: Deploy OBM global configuration
  template: src=00-global.ini dest=/etc/obm/conf/00-global.ini
  tags: obm-conf
