---
- name: Deploy local OBM PostgreSQL permissions
  template: src=01-local-obm dest={{ pgdatadir }}/pg_hba.d/01-local-obm
  delegate_to: "{{ obm_db_master_host }}"
  notify:
    - Merge PostgreSQL configuration files
  tags: obm-db

- name: Copy Postgres SQL scripts
  template: src=setup.sql dest={{ scriptsdir }}/{{ item }}
  with_items:
   - setup.sql
   - lang.sql
  delegate_to: "{{ obm_db_master_host }}"
  tags: obm-db

- name: Disable requiretty
  lineinfile: >
   dest=/etc/sudoers
   regexp=^Defaults.*requiretty
   line="#Defaults    requiretty"
  tags: obm-db

- name: Create OBM postgres user
  postgresql_user:
   name={{ obm_db_user }}
   password={{ obm_db_password }}
   role_attr_flags=CREATEDB,NOSUPERUSER,NOCREATEROLE
  sudo: yes
  sudo_user: postgres
  delegate_to: "{{ obm_db_master_host }}"
  tags: obm-db

- name: Create OBM database
  postgresql_db:
   name={{ obm_db_name }}
   owner={{ obm_db_user }}
   encoding='UTF-8'
  sudo: yes
  sudo_user: postgres
  delegate_to: "{{ obm_db_master_host }}"
  notify:
    - Reload Postgres
    - Init Postgres database
  tags: obm-db

- name: Enable requiretty
  lineinfile: >
   dest=/etc/sudoers
   regexp=^#Defaults.*requiretty
   line="Defaults    requiretty"
  tags: obm-db
