---
- name: Deploy local OBM PostgreSQL permissions
  template: src=01-local-obm dest={{ datadir }}/pg_hba.d/01-local-obm
  delegate_to: "{{ db_master_host }}"
  notify:
    - Merge PostgreSQL configuration files
  tags: obm-db

- name: Copy Postgres SQL scripts
  template: src={{ item }} dest={{ scriptsdir }}/{{ item }}
  with_items:
   - setup.sql
   - lang.sql
   - murder_user.sql
  delegate_to: "{{ db_master_host }}"
  tags: obm-db

- name: Create OBM postgres user
  postgresql_user:
   name={{ db_user }}
   password={{ db_pass }}
   role_attr_flags=CREATEDB,NOSUPERUSER,NOCREATEROLE
  sudo: yes
  sudo_user: postgres
  delegate_to: "{{ db_master_host }}"
  tags: obm-db

- name: Create OBM database
  postgresql_db:
   name={{ db_name }}
   owner={{ db_user }}
   encoding='UTF-8'
  sudo: yes
  sudo_user: postgres
  delegate_to: "{{ db_master_host }}"
  notify:
    - Merge PostgreSQL configuration files
    - Reload Postgres
    - Init OBM2 Postgres database
    - Init OBM3 Postgres database
  tags: obm-db
