---
#
# Global configuration file
#

### OBM configuration ####

# OBM version
#obm_version: 2.5.7

# Public URL of the OBM web interface
obm_external_url: obm.example.com

# Database configuration (either PGSQL or MYSQL) (default: PGSQL)
obm_db_type: PGSQL

# The server hosting the database or the SQL load balancer
obm_db_host: obm.example.com

# The server hosting the database or the master of replication
obm_db_master_host: "{{ obm_db_host }}"

# Database configuration
obm_db_user: obm
obm_db_password: obm
obm_db_name: obm

# Language of the database (fr/en)
obm_language: fr

# Make default ldap different from the first member of
# the ldapservers group (strange but supported)
#obm_ldap_host: obm.example.com
#obm_ldap_port: 389
#obm_ldap_ssl: no
#obm_ldap_suffix: "dc=local"

# Customize user in charge of authenticating users
#obm_ldap_bind_dn: "uid=ldapadmin,ou=sysusers,{{ obm_ldap_suffix }}"
#obm_ldap_bind_pw: "mdp3PaAL"

# SASL Backend (allowed values : ldap, pam)
#obm_sasl_backend: "ldap"

# SASL search filter
#obm_sasl_ldap_filter: "(|(&(mailBox=%U@%d)(objectClass=obmUser)(mailAccess=PERMIT))(&(uid=%U)(cn=Administrator Cyrus)(objectClass=posixAccount)))"

#### IMAP / SMTP configuration ####
## Globally enable legacy SSL on Messaging services
## by default, only TLS on standard ports will be enable (more secure)
#obm_enable_legacy_ssl: "no"
## Enable POP services (discouraged because it makes backups very difficult)
#obm_enable_pop: "no"

#### IMAP Cluster Configuration ####
## Clustering is automatically enabled if you set a cyrusmupdateserver
## in your inventory.
## You need to set a user for cluster synchronisation. murder will by
## used by default.
#obm_mupdate_user: murder
#obm_mupdate_pass: murder

#### SSL certificates ####
## If you need a different certificate for an host or a particular
## service, you can override ca_file, cert_file and key_file
## variables in group_vars or host_vars folders.
##
## Default values are specified below
#obm_ca_file:   /var/lib/obm-ca/cacert.pem
#obm_cert_file: /etc/obm/certs/obm_cert.pem
#obm_key_file:  /etc/obm/certs/obm_cert.pem

#### Global NTP server (if needed) ####
## You probably need it if you use mirror mode
#ntp_server: 192.168.122.1

#### Packages mode (default: internet) ####
## Allows you to deploy your architecture without internet access
##
##  internet : get packages from internet repositories (the default)
##  mirror   : add all repositories hostnames in /etc/hosts and make
##             them point to `packages_mirror_ip`.
##  rsync    : rsync resources/rpm-repos directory and install from it [not implemented yet]
##
#packages_mode: internet
#packages_mirror_ip: 192.168.122.1

#### OBM-Autoconf extensions ####

# Postfix variables
smtp_in_hostname: "obm.example.com"
smtp_in_mynetworks: ""
smtp_in_relayhost: ""
smtp_in_submission: "yes"
smtp_in_smtps: "no"
smtp_in_ssl: "no"

#### OBM-UI ####
remove_banner: "yes"

#### Proxy Configuration ####
# Will be deployed on all remote hosts
#proxy_host:
#proxy_port:
#proxy_username:
#proxy_password:

