---
- hosts: all
  user: root

  tasks:
  - name: Install Postgresql Server
    yum: pkg={{ item }} state=present
    with_items: 
     - postgresql91-server
     - obm-PostgreSQL

  - name: Copying exported_variables files 
    copy: src=../var/{{ item }} dest=/tmp/{{ item }}
    with_items:
     - exported_variables

  - name: Copying install and configuration scripts
    copy: src=../scripts/{{ item }} dest=/tmp/{{ item }}
    with_items:
     - generate_obm-admin.expect

  - name: Generate OBM scripts
    shell: /bin/bash /tmp/generate_obm-admin.expect

  - name: Configuration OBM Database
    shell: /usr/bin/expect -d /tmp/obm-admin.expect > /var/log/expect-obm-admin.log 2>&1
    
    
#  - name: Install OBM Database
#    yum: pkg={{item}} state=present
