---
- name: Deploy master.cf configuration
  copy: src={{ item }} dest=/etc/master_cf.d/{{ item }} mode=0644
  with_items:
   - 10-submission_master.cf
   - 20-smtps_master.cf
  notify:
    - Merge master.cf configuration files
    - Fix perms on master.cf
  tags: postfix

- name: Check if main.cf exists
  stat: path=/etc/main.cf
  register: maincf_file
  tags: postfix

- name: Deploy main.cf templates configuration
  template: src={{ item }} dest=/etc/main_cf.d/{{ item }} mode=0644
  with_items:
   - 10-relayhost_main.cf
   - 60-smtps_main.cf
  notify:
    - Merge main.cf configuration files
    - Fix perms on main.cf
  tags: postfix

- name: Enable postfixSmtpInMaps and postfixAccess obm-satellite modules
  shell: /usr/sbin/osenmod {{ item }}
  with_items:
   - postfixSmtpInMaps
   - postfixAccess
  notify:
   - Restart OBM-Satellite service
  tags: postfix

- name: Add user postfix in saslauth group
  user: name=postfix groups=saslauth append=yes
  notify:
   - Restart postfix service
  when: ansible_os_family == "RedHat"
  tags: postfix
