---
- name: Enable Apache2 modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
      - ssl
      - proxy
      - proxy_http
      - proxy_ajp
      - rewrite
  notify: Restart Apache
  tags: obm-ui
