---
- name: YUM Install OBM-UI and Apache server
  yum: pkg={{ item }}
  with_items:
   - obm-ui
   - mod_ssl
   - obm-services
   - php-pecl-apc
   - php-pecl-imagick
  when: ansible_pkg_mgr == "yum"
  tags: obm-ui

- name: APT Install OBM-UI and Apache server
  apt: pkg={{ item }}
  with_items:
   - obm-ui
   - obm-services
   - php-apc
   - php5-imagick
  when: ansible_pkg_mgr == "apt"
  tags: obm-ui
