---
- name: Deploy OBM VirtualHost
  template: src=obm.conf dest=/etc/httpd/conf.d/obm.conf
  register: command_result
  tags: obm-ui

- name: Start Apache service
  service: name=httpd state=started enabled=yes
  when: command_result.changed
  tags: obm-ui
