---
# Fix jetty6 init script (refers http://ci-obm.linagora.com/jira/browse/OBMFULL-5592)
- name: Fix jetty6 init script
  lineinfile: >
   line="	exit $?"
   dest=/etc/init.d/jetty6
   insertafter=".*status -p.*"
  when: major_version | version_compare('3.0', '<')
  notify: 
      - Restart Jetty
  tags: spushnik

- name:  Deploy healthcheck.ini configuration
  template: src={{ item }} dest=/etc/obm/healthcheck_ini.d/{{ item }} mode=0644
  with_items:
   - 03-SPUSHNIK_healthcheck.ini
  delegate_to: "{{ ui_host }}"
  notify:
   - Merge healthcheck.ini configuration file
   - Fix perms on healthcheck.ini
  tags: spushnik
