---
- name: Add Datastax APT GPG key [without proxy]
  apt_key: >
    url=http://debian.datastax.com/debian/repo_key
    state=present
  when: mode == "internet" and proxy_host is not defined
  tags: cassandra

- name: Add Datastax APT GPG key [with proxy]
  apt_key: >
    url=http://debian.datastax.com/debian/repo_key
    state=present
  environment: proxy_env
  when: mode == "internet" and proxy_host is defined
  tags: cassandra

- name: APT Enable Datastax repository
  copy: >
      src=datastax.list
      dest=/etc/apt/sources.list.d/datastax.list
      mode=0644
  notify: Update DEB cache
  when: ansible_distribution == "Debian"
  tags: cassandra
