---
- include: include_vars.yml
- include: yum_repositories.yml
  when: ansible_pkg_mgr == "yum"
- include: apt_repositories.yml
  when: ansible_pkg_mgr == "apt"
- include: flush.yml
- include: packages.yml
- include: config.yml
- include: flush.yml
