---
- name: Deploy local OBM PostgreSQL Permissions
  template: src=03-remote-obm-autoconf dest={{ pgdatadir }}/pg_hba.d/03-remote-obm-autoconf
  delegate_to: "{{ obm_db_master_host }}"
  # If there is a load balancer, the master should let only the load balancer
  # and the slaves connect
  when: not has_sql_load_balancer
  tags: obm-autoconf

- name: Merge PostgreSQL configuration files
  assemble: src={{ pgdatadir }}/pg_hba.d dest={{ pgdatadir }}/pg_hba.conf
  delegate_to: "{{ obm_db_master_host }}"
  when: not has_sql_load_balancer
  notify:
    - Reload Postgres
  tags: obm-ui
