---
- name: Restart OPush2
  service: name=jetty6 enabled=yes state=restarted
  when: major_version | version_compare('3.0', '<')
  tags: opush

- name: Start OPush2
  service: name=jetty6 enabled=yes state=started
  when: major_version | version_compare('3.0', '<')
  tags: opush

- name: Restart OPush3
  service: name=opush enabled=yes state=restarted
  when: major_version | version_compare('3.0', '>=')
  tags: opush

- name: Start OPush3
  service: name=opush enabled=yes state=started
  when: major_version | version_compare('3.0', '>=')
  tags: opush
