---
- name: Restart Cassandra server
  service: name=cassandra state=restarted
  tags: cassandra

- name: Run Cassandra initialization script
  command: cqlsh -u cassandra -p cassandra -f /etc/cassandra/init.cql {{ hostvars[inventory_hostname] | get_ip(lan_net) }}
  register: command_result
  retries: 60
  delay: 2
  until: command_result.rc != 1
  tags: cassandra
