---
- name: Restart Cassandra server
  service: name=cassandra state=restarted
  tags: cassandra

- name: Run Cassandra initialization script
  command: cqlsh -u cassandra -p cassandra -f /etc/cassandra/init.cql {{ ansible_default_ipv4['address'] }}
  register: command_result
  retries: 60
  delay: 2
  until: command_result.rc != 1
  tags: cassandra
