---
- name: Init Postgres database
  command: psql -f {{ scriptsdir }}/{{item}}
  environment: pg_env
  with_items:
   - setup.sql
   - create_obmdb_{{ obm_major_version }}.pgsql.sql
   - obmdb_default_values_{{ obm_major_version }}.sql
   - data-{{ obm_language }}/obmdb_ref_{{ obm_major_version }}.sql
   - data-{{ obm_language }}/obmdb_nafcode_{{ obm_major_version }}.sql
   - obmdb_prefs_values_{{ obm_major_version }}.sql
   - lang.sql
  delegate_to: "{{ obm_db_master_host }}"
  tags: obm-db
