---
- name: Deploy pam configuration
  template: src=pam dest=/etc/pam.d/{{ item }} backup=yes
  with_items:
   - smtp
  when: sasl_backend == "pam"
  notify:
   - Restart saslauthd
  tags: postfix-common
