---
- name: DEBCONF Configure OBM external url
  debconf: >
      name=obm-conf
      question=obm-conf/externalurl
      "value={{ external_url }}"
      vtype=string
  tags: obm-locator

- name: DEBCONF Configure OBM ldap server
  debconf: >
      name=obm-conf
      question=obm-conf/ldapserver
      "value={{ ldap_master_host }}"
      vtype=string
  tags: obm-locator

- name: DEBCONF Configure OBM db type
  debconf: >
      name=obm-conf
      question=obm-conf/dbtype
      "value={{ db_type }}"
      vtype=select
  tags: obm-locator

- name: DEBCONF Configure OBM db host
  debconf: >
      name=obm-conf
      question=obm-conf/dbhost
      "value={{ db_host }}"
      vtype=string
  tags: obm-locator

- name: DEBCONF Configure OBM db name
  debconf: >
      name=obm-conf
      question=obm-conf/dbname
      "value={{ db_name }}"
      vtype=string
  tags: obm-locator

- name: DEBCONF Configure OBM db user
  debconf: >
      name=obm-conf
      question=obm-conf/dbuser
      "value={{ db_user }}"
      vtype=string
  tags: obm-locator

- name: DEBCONF Configure OBM db password
  debconf: >
      name=obm-conf
      question=obm-conf/dbpasswd
      "value={{ db_pass }}"
      vtype=string
  tags: obm-locator

- name: DEBCONF Configure OBM db password (2)
  debconf: >
      name=obm-conf
      question=obm-conf/dbpasswd_verify
      "value={{ db_pass }}"
      vtype=string
  tags: obm-locator
