---
- name: YUM Install OBM-Locator Server
  yum: pkg=obm-locator
  when: ansible_pkg_mgr == "yum"
  tags: obm-locator

- name: APT Install OBM-Locator Server
  apt: pkg=obm-locator
  when: ansible_pkg_mgr == "apt"
  tags: obm-locator
