---
- name: Install obm-cert
  yum: name=obm-cert
  register: command_result
  tags: obm-cert

- name: Create OBM certificate
  command: >
      creates=/etc/obm/certs/{{ obm_external_url }}_signed.pem
      /usr/share/obm-ca/createcert.sh "{{ obm_external_url }}"
  when: command_result.changed
  tags: obm-cert

- name: Set the OBM certificate symlink
  file: >
      src=/etc/obm/certs/{{ obm_external_url }}_signed.pem
      dest=/etc/obm/certs/obm_cert.pem
      state=link
  tags: obm-cert
