---
# file: roles/obm-satellite/tasks/obm-satellite.yml

- name: Start OBM-Satellite service
  service: name={{ item }} state=started
  with_items:
   - obm-satellite

- name: Configure OBM-Satellite startup
  action: command /sbin/chconfig {{ item.command }} {{ item.status }}
  with_items:
   - { command: 'obm-satellite', status: 'on' }

