---
- name: Add a CA certificate to OBM-Autoconf client
  lineinfile: >
      line="certs.push({file: {{ ca_file | basename}}})"
      dest={{ autoconf_client_dir }}/modules/certs/certs.jsm
      state=present
  delegate_to: "{{ autoconf_host }}"
  when: groups['autoconfservers'][0] is defined
  tags: obm-autoconf

- name: Build OBM-Autoconf client
  shell: >
      zip -r {{ xpi_dir }}/obm-autoconf-client.xpi {{ autoconf_client_dir }}/*
  delegate_to: "{{ autoconf_host }}"
  when: groups['autoconfservers'][0] is defined
  tags: obm-autoconf
