---
- name: Add a generic CA cert to OBM-Autoconf configuration
  lineinfile: >
      line="certs.push({file: cacert.pem})"
      regexp="^certs\.push.*cacert.pem"
      dest="{{ autoconf_client_dir }}/modules/certs/certs.jsm"
      state=present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['autoconfservers'] }}"
  when: groups['autoconfservers'][0] is defined
  tags: obm-autoconf

- name: Add a custom CA cert to OBM-Autoconf configuration
  lineinfile: >
      line="certs.push({file: {{ ca_file | basename }}})"
      dest="{{ autoconf_client_dir }}/modules/certs/certs.jsm"
      state=present
  delegate_to: "{{ item }}"
  with_items: "{{ groups['autoconfservers'] }}"
  when: groups['autoconfservers'][0] is defined
  tags: obm-autoconf

- name: Build OBM-Autoconf client
  shell: >
      zip -r {{ xpi_dir }}/obm-autoconf-client.xpi {{ autoconf_client_dir }}/*
  delegate_to: "{{ item }}"
  with_items: "{{ groups['autoconfservers'] }}"
  when: groups['autoconfservers'][0] is defined
  tags: obm-autoconf
