---
- name: Deploy cyrus.conf configuration
  copy: src={{ item }} dest=/etc/cyrus_conf.d/{{ item }} mode=0644
  with_items:
   - 01-header_cyrus.conf
   - 11-services_cyrus.conf
   - 21-events_cyrus.conf
  notify:
    - Merge cyrus.conf configuration files
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  tags: cyrus-murder

- name: Deploy imapd.conf configuration (debug)
  copy: src={{ item }} dest=/etc/imapd_conf.d/{{ item }} mode=0644
  with_items:
   - 50-debug_imapd.conf
  notify:
    - Merge imapd.conf configuration files
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  tags: cyrus-murder

- name: Add the murder account as an cyrus admin
  lineinfile: >
   dest=/etc/imapd.conf
   regexp='^admins:.*'
   line="admins: cyrus {{ mupdate_username }}"
  notify:
    - Fix perms on Cyrus configuration files
    - Restart Cyrus-Imapd service
  tags: cyrus-murder

- name: Create murder system user
  user: name=murder
  when: use_murder == "yes"
  tags: cyrus-murder

- name: Set cyrus password
  shell: echo {{ item.password }}|passwd --stdin {{ item.password }}
  with_items:
   - { user: cyrus, password: "{{ cyrus_password }}" }
   - { user: murder, password: "{{ murder_password }}" }
  tags: cyrus-murder

