---
- hosts: all
  user: root

  tasks:
  - name: Disable some system services
    shell: /bin/sed -i s/SELINUX=.*/SELINUX\=disabled/g /etc/selinux/config

  - name: Disbale SELinux
    shell: /usr/sbin/setenforce 0

  - name: Disable ipv6
    shell: echo -e "\n#Disable ipv6\nnet.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
  
  - name: Add some utils
    yum: pkg={{ item }} state=present
    with_items:
     - vim
     - mlocate
     - wget
     - curl
     - libselinux-python
     - policycoreutils-python
     - expect

  - name: Add Postgresql repo
    yum: name=http://yum.postgresql.org/9.1/redhat/rhel-6-x86_64/pgdg-centos91-9.1-4.noarch.rpm state=present
  
  - name: Add OBM repo
    yum: name=http://packages.obm.org/rpm/25/release/obm-release.noarch.rpm state=present 

  - name: Add EPEL repo
    yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present 

