---
- name: Add host name to hosts file
  lineinfile: >
   line="127.0.0.1   {{ item }}"
   dest=/etc/hosts
   insertafter=BOF
  with_items:
   - "{{ inventory_hostname }}"
   - "{{ obm_ldap_host }}"
  tags: hosts

- name: Cleanup hosts file if needed
  lineinfile: >
   regexp=".*{{ item }}"
   dest=/etc/hosts
   state=absent
  with_items:
   - mirror.centos.org
   - download.fedoraproject.org
   - packages.obm.org
   - yum.postgresql.org
  when: packages_mode == "internet"
  tags: hosts
