---
- name: Add host name to hosts file
  lineinfile: >
   line="127.0.0.1   {{ inventory_hostname }}"
   dest=/etc/hosts
   insertafter=BOF
  tags:
      - common
      - hosts

- name: Cleanup hosts file if needed
  lineinfile: >
   regexp=".*{{ item }}"
   dest=/etc/hosts
   state=absent
  with_items:
   - mirror.centos.org
   - download.fedoraproject.org
   - packages.obm.org
   - yum.postgresql.org
  when: mode == "internet"
  tags:
      - common
      - hosts
