---
- name: Ensure IPTables packages are  installed
  yum: pkg=system-config-firewall-base state=present
  tags:
      - common
      - iptables

- name: Stop IPTables services
  service: name={{ item }} state=stopped enabled=no
  with_items:
   - iptables
   - ip6tables
  tags:
      - common
      - iptables
