---
# Currenly, libselinux must be installed for offline deployment
#- name: Deploy libselinux-python RPM (mirror mode)
#  copy: >
#      src=resources/libselinux-python-2.0.94-5.3.el6_4.1.x86_64.rpm
#      dest=/tmp/libselinux-python-2.0.94-5.3.el6_4.1.x86_64.rpm
#  when: mode == "mirror"
#  tags: repositories
#
#- name: Install libselinux-python (mirror mode)
#  yum: name=/tmp/libselinux-python-2.0.94-5.3.el6_4.1.x86_64.rpm
#  when: mode == "mirror"
#  tags: repositories
#
- name: YUM libselinux-python (internet mode)
  yum: name={{ selinux_python_package }}
  when: mode == "internet" and ansible_pkg_mgr == "yum"
  tags:
      - common
      - libselinux

- name: APT python-selinux (internet mode)
  apt: name={{ selinux_python_package }}
  when: mode == "internet" and ansible_pkg_mgr == "apt"
  tags:
      - common
      - libselinux
