---
- name: Enable UTF-8 locales
  locale_gen: >
      name={{ item }}
      state=present
  with_items:
   - en_US.UTF-8
   - en_GB.UTF-8
   - fr_FR.UTF-8
  when: ansible_pkg_mgr == "apt"
  tags:
      - common
      - locales
