---
- name: Approximate date using local host
  command: date -u +%m%d%H%M
  register: command_result
  delegate_to: localhost
  tags:
      - common
      - ntp

- name: Set approximate system date
  command: date -u "{{ command_result.stdout_lines[0] }}"
  register: command_result
  tags:
      - common
      - ntp

- name: Install NTP server
  yum: pkg=ntp
  tags:
      - common
      - ntp

- name: Start NTP server
  service: name=ntpd state=started enabled=yes
  notify:
   - Update system date
  tags:
      - common
      - ntp

- name: NTP Server configuration cleanup
  lineinfile: dest=/etc/ntp.conf regexp="server {{ item }}\." state=absent
  with_items:
   - 0
   - 1
   - 2
   - 3
  when: ntp_server is defined
  notify:
   - Restart NTP service
   - Update system date
  tags:
      - common
      - ntp

- name: NTP Server configuration update
  lineinfile: >
   dest=/etc/ntp.conf
   line="server {{ ntp_server }} iburst"
  notify:
   - Restart NTP service
   - Update system date
  when: ntp_server is defined
  tags:
      - common
      - ntp
