---
- name: Install some common and usefull packages
  yum: pkg={{ item }} state=present
  with_items:
   - vim
   - mlocate
   - wget
   - curl
   - libselinux-python
   - policycoreutils-python
   - expect
   - tmux
  tags: packages

