---
- name: Install some common and useful packages
  yum: pkg={{ item }}
  with_items:
   - vim
   - mlocate
   - wget
   - curl
   - policycoreutils-python
   - tmux
   - man
   - htop
   - atop
   - strace
   - screen
   - rsync
   - bind-utils
  tags: packages
