---
- name: Install some common and useful packages
  yum: pkg={{ item }} state=present
  with_items:
   - vim
   - mlocate
   - wget
   - curl
   - libselinux-python
   - policycoreutils-python
   - expect
   - tmux
   - man
  tags: packages

