---
- name: Remove bridge-nf-call
  sysctl: name=net.bridge.bridge-nf-call-{{ item }} value=0 reload=no
  with_items:
   - ip6tables
   - iptables
   - arptables
  tags: sysctl ipv6

- name: Disable IPv6
  sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1 sysctl_set=yes 
  tags: sysctl ipv6
