---
- name: Check OBM version
  debug: "msg='Configured OBM version : {{ version }} - major : {{ major_version }} - short : {{ short_version }}'"
  failed_when: short_version != '25'
  tags:
      - common
      - version
