---
- name: Enable YUM keepcache option
  lineinfile: >
    dest=/etc/yum.conf
    regexp="^keepcache=0$"
    line="keepcache=1"
    backrefs=yes
  tags:
      - common
      - yum

- name: Enable YUM proxy option
  lineinfile: >
    dest=/etc/yum.conf
    regexp="^proxy=.*$"
    line="proxy=http://{{ prx_host }}:{{ prx_port }}/"
  when: proxy_host is defined
  tags:
      - common
      - yum

- name: Disable YUM proxy option
  lineinfile: >
    dest=/etc/yum.conf
    regexp="^proxy=.*$"
    state=absent
  when: proxy_host is not defined
  tags:
      - common
      - yum

- name: Enable YUM proxy ACL
  lineinfile: >
   dest=/etc/yum.conf
   regexp="^{{item.var}}=.*$"
   line="{{ item.var }}={{ item.value }}"
  with_items:
      - { var: proxy_username, value: "{{ prx_username }}" }
      - { var: proxy_password, value: "{{ prx_password }}" }
  when: proxy_username is defined
  tags:
      - common
      - yum

- name: Disable YUM proxy ACL
  lineinfile: >
   dest=/etc/yum.conf
   regexp="^{{ item }}=.*$"
   state=absent
  with_items:
      - prx_username
      - prx_password
  when: proxy_username is not defined
  tags:
      - common
      - yum

- name: Check if Yum releasever file exists
  stat: path=/etc/yum/vars/releasever
  register: releasefile
  when: ansible_os_family == "RedHat"

- name: Create Yum releasever file if missing
  lineinfile: >
    line="{{ ansible_distribution_major_version }}"
    dest=/etc/yum/vars/releasever
    create=true
  when: ansible_os_family == "RedHat" and releasefile.stat.isfile is not defined

- name: Correct Yum releasever
  lineinfile: >
    regexp="^(\d+)\..*"
    line="\1"
    dest=/etc/yum/vars/releasever
    backrefs=yes
  when: ansible_os_family == "RedHat"
  tags:
      - common
      - yum
