---
- name: YUM Install OBM Solr Server
  yum: pkg=obm-solr state=present
  notify:
    - Update Tomcat triggers
  when: ansible_pkg_mgr == "yum"
  tags: obm-solr

- name: APT Install OBM Solr Server
  apt: pkg=obm-solr state=present
  notify:
    - Update Tomcat triggers
  when: ansible_pkg_mgr == "apt"
  tags: obm-solr
