---
- name: Install Solr Server
  yum: pkg=obm-solr state=present
  notify:
    - Update Tomcat triggers
  tags: obm-solr

- name: Correct OBM-Tomcat init-script
  lineinfile: >
   line="jps=$JAVA_HOME/bin/jps"
   dest=/etc/init.d/obm-tomcat
   state=absent
  tags: obm-solr
