---
- name: Deploy OBM Automaton configuration
  template: src=03-sync.ini dest=/etc/obm/conf/03-sync.ini
  tags: obm-sync

- name: Merge OBM configuration files
  assemble: src=/etc/obm/conf dest=/etc/obm/obm_conf.ini backup=yes
  tags: obm-sync

- name: Create OBM-Sync configuration file
  template: src=obm-sync.xml dest=/etc/obm-tomcat/applis/obm-sync.xml
  notify:
      - Update Tomcat triggers
  tags: obm-sync

- name: Fix perms on obm_conf.ini
  file: path=/etc/obm/obm_conf.ini mode=0644
  tags: obm-sync
