---
- name: Deploy obm-sync PostgreSQL permissions
  template: src=03-remote-obm-sync dest={{ datadir }}/pg_hba.d/03-remote-obm-sync
  delegate_to: "{{ db_master_host }}"
  notify:
    - Merge PostgreSQL configuration files
  tags: obm-sync
