---
## TODO: UPDATE THESE TASKS TO MAKE THEM RE-RUNNABLE

- name: Initialize PostgreSQL Server
  command: /etc/init.d/postgresql-9.1 initdb

- name: Start PostgreSQL service
  service: name=postgresql-9.1 state=started enabled=yes

- name: Copy install and configuration script
  template: src=obm-admin.expect dest=/tmp/obm-admin.expect

- name: Symlink for obm-admin
  action: file src={{ item.src }} dest={{ item.dest }} state=link
  with_items:
   - { src: '/etc/init.d/postgresql-9.1', dest: '/etc/init.d/postgresql' }
   - { src: '/var/lib/pgsql/9.1/data', dest: '/var/lib/pgsql/data' }

- name: Configure OBM Database
  shell: expect -f /tmp/obm-admin.expect > /var/log/expect-obm-admin.log 2>&1

