---
- name: Deploy Postgres repository RPM (proxy mode)
  copy: >
      src=resources/pgdg-centos91-9.1-4.noarch.rpm
      dest=/root/pgdg-centos91-9.1-4.noarch.rpm
  when: packages_mode == "proxy"
  tags: postgres

- name: Enable Postgres repository (proxy mode)
  yum: name=/root/pgdg-centos91-9.1-4.noarch.rpm
  when: packages_mode == "proxy"
  tags: postgres

- name: Spoof Postgres repository hostname in /etc/hosts (proxy mode)
  lineinfile: >
              dest=/etc/hosts
              regexp='.*yum\.postgresql\.org$'
              line="{{ packages_proxy_ip }}    yum.postgresql.org"
  when: packages_mode == "proxy"
  tags: postgres

- name: Enable Postgresql 9.1 Repository (internet mode)
  yum: name=http://yum.postgresql.org/9.1/redhat/rhel-6-x86_64/pgdg-centos91-9.1-4.noarch.rpm
  when: packages_mode == "internet"
  tags: postgres

- name: Remove any Postgres hostname spoofing (internet mode)
  lineinfile: >
              dest=/etc/hosts
              regexp='.*yum\.postgresql\.org$'
              state=absent
  when: packages_mode == "internet"
  notify:
   - Clean yum repositories
  tags: postgres
