---
- name: Deploy cyrus.conf configuration
  copy: src={{ item }} dest=/etc/cyrus_conf.d/{{ item }} mode=0644
  with_items:
   - 01-header_cyrus.conf
   - 11-services_cyrus.conf
   - 21-events_cyrus.conf
  notify:
    - Merge cyrus.conf configuration files
  tags: cyrus-common

- name: Check if imapd.conf exists
  stat: path=/etc/imapd.conf
  register: imapd_file

- name: Deploy imapd.conf configuration
  copy: src={{ item }} dest=/etc/imapd_conf.d/{{ item }} mode=0644
  with_items:
   - 30-tls_imapd.conf
  notify:
    - Merge imapd.conf configuration files
  tags: cyrus-common

- name: Set cyrus password
  shell: echo {{ cyrus_password }}|passwd --stdin cyrus
  tags: cyrus-backend

#- name: Restart Cyrus-Imapd Service
#  service: name=cyrus-imapd state=restarted
#  tags: cyrus-backend

- name: Enable cyrus-partition obm-satellite module
  shell: /usr/sbin/osenmod cyrusPartition
  notify:
   - Restart OBM-Satellite service
  tags: cyrus-backend
