---
- name: Create cyrus.conf directory
  file: name=/etc/cyrus_conf.d state=directory
  tags: cyrus-common

- name: Deploy cyrus.conf configuration
  copy: src={{ item }} dest=/etc/cyrus_conf.d/{{ item }}
  with_items:
   - 00-header_cyrus.conf
   - 10-services_cyrus.conf
   - 20-events_cyrus.conf
   - 30-footer_cyrus.conf
  tags: cyrus-common

- name: Create imapd.conf directory
  file: name=/etc/imapd_conf.d state=directory
  tags: cyrus-common

- name: Deploy imapd.conf configuration
  copy: src={{ item }} dest=/etc/imapd_conf.d/{{ item }}
  with_items:
   - 10-main_imapd.conf
   - 20-partitions_imapd.conf
  tags: cyrus-common

